name: CI

on:
  workflow_dispatch:
    inputs:
      environment:
        type: environment
        description: Select the environment
      choice:
        type: choice
        description: Would you like to bump the version?
        options:
        - No
        - Major
        - Minor
        - Patch
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: greet
        run: | 
          echo "environment is ${{ github.event.inputs.environment }}"
          echo "boolean is ${{ github.event.inputs.boolean }}"
          echo "choice is ${{ github.event.inputs.choice }}"
