name: Conditional job Selection based on input

on:      
  workflow_dispatch:
    inputs:
      job-name:
        description: 'Job id'
        required: true

jobs:
  build:
    name: build
    # if: ${{ github.event.inputs.job-name == 'build' }}
    runs-on: ubuntu-latest
    
    steps:

    - uses: actions/checkout@v2
    
    - name: echo
      run: |
       echo "this is build job" 
     

    - name: Bump version and push tag
      uses: jaumann/github-bumpversion-action@v0.0.7
      env:
        GITHUB_TOKEN: "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"
        DEFAULT_BUMP: patch
