name: Conditional job Selection based on input

on:      
  workflow_dispatch:
    inputs:
      job-name:
        description: 'Job id'
        required: true

jobs:
  build:
    name: build
    # if: ${{ github.event.inputs.job-name == 'build' }}
    runs-on: ubuntu-latest
    
    steps:

    - uses: actions/checkout@v2
    
    - name: echo
      run: |
        echo "this is build job" 
     
    - name: git version
      run: git --version

    - name: work around permission issue
      run: git config --global --add safe.directory /github/workspace

#    - name: Bump version and push tag
#      uses: jaumann/github-bumpversion-action@v0.0.7
#      env:
#        GITHUB_TOKEN: "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"
#        DEFAULT_BUMP: patch

    - name: Bump version and push tag
      uses: anothrNick/github-tag-action@1.36.0
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        WITH_V: true
        DEFAULT_BUMP: patch
